"""Add geolocation to users and merchants

Revision ID: 0af5b61d6cba
Revises: 0015
Create Date: 2026-06-03 15:29:24.192758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0af5b61d6cba'
down_revision: Union[str, None] = '0015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('merchants', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('merchants', 'longitude')
    op.drop_column('merchants', 'latitude')
    # ### end Alembic commands ###

